import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer, Header } from "@/components/common";
import dynamic from "next/dynamic";
import { i18n, Locale } from "@/lib/i18n-config";

const ThemeProvider = dynamic(
  () => import("@/components/providers/theme_provider")
);
const LanguageProvider = dynamic(
  () => import("@/components/providers/language_provider")
);

const schriftedSans = localFont({
  src: "/fonts/schrifted_regular.woff",
  variable: "--font-schrifted-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={params.lang}>
      <body className={`${schriftedSans.variable} , antialiased`}>
        <LanguageProvider
          lang={{
            lang: params.lang,
          }}
        >
          <ThemeProvider>
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
