import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer, Header } from "@/components/common";
import dynamic from "next/dynamic";

const ThemeProvider = dynamic(
  () => import("@/components/providers/theme_provider")
);

const schriftedSans = localFont({
  src: "/fonts/schrifted_regular.woff",
  variable: "--font-schrifted-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${schriftedSans.variable} , antialiased`}>
        <ThemeProvider>
          <Header />
          {children}
          {/* <Footer /> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
